### ISSUE TITLE
App name on iOS home screen changed to "baha"

### ISSUE THREAD

**Issue by StevenSchifter** [arashpayan/prayer-book#28]
On my iPhone XS running iOS 15.3.1, I noticed that the name of the Prayer Book app on my home screen unexpectedly changed to "baha". Could you please investigate this issue? Thanks.

![IMG_1072](https://user-images.githubusercontent.com/70248147/153726156-5a423d3b-3fca-4d38-8c14-76afcf520889.PNG)

**Comment by arashpayan** [comment]
Hi @StevenSchifter. That's really weird. I use an Android phone nowadays, so I didn't know about this. I was able to reproduce it on my development iPhone. Do you have any idea when this started happening? Did it coincide with the upgrade to iOS 15?

**Comment by StevenSchifter** [comment]
Yes, I think this issue started after I upgraded to iOS 15.

**Comment by StevenSchifter** [comment]
Thanks for fixing this issue and adding dark mode support.

**Comment by StevenSchifter** [comment]
Thanks for fixing this issue and adding dark mode support.

**Comment by arashpayan** [comment]
I was happy to finally have some time to work on it. :grin:
